version: '3.9'

services:
  database:
      image: bitnami/postgresql
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USERNAME=docker
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DATABASE=app
      volumes:
        - postgresql_data:/bitnami/postgresql
      networks:
        - wallet_net
  api:
    image: wallet-api:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgresql://docker:docker@database:5432/app?schema=public
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - wallet_net
  storage:
    image: minio/minio
    ports:
      - 9000:9000
      - 41277:41277
    environment:
      MINIO_ROOT_USER: 2408884f697a9eb79ae1c7019c91e49c
      MINIO_ROOT_PASSWORD: f06bb22ad1cd001061bb45db565ba3a1
      MINIO_REGION: us-east-2
      MINIO_HTTP_PORT: 9000
    command: minio server /data --console-address 0.0.0.0:41277
    volumes:
     - ./minio-data:/data

networks:
  wallet_net:
    driver: bridge

volumes:
  postgresql_data:
    driver: locals